set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1230.340 -nets VDD -layer M2 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 169.680 -nets VDD -layer M2 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1227.810 -nets VDD -layer M3 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 173.200 -nets VDD -layer M3 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1228.670 -nets VSS -layer M2 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 171.350 -nets VSS -layer M2 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1226.190 -nets VSS -layer M3 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 174.820 -nets VSS -layer M3 -width 1.220 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 214.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 256.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 298.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 340.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 382.985 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 424.985 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 467.385 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 509.385 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 551.785 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 593.785 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 636.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 678.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 720.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 762.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 804.985 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 846.985 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 889.385 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 931.385 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 973.785 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1015.785 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1058.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1100.185 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1142.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1184.585 -nets VDD  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 172.590 -start_high_ends coordinate  -start_high_ends_coordinate 1228.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 215.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 257.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 299.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 341.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 383.835 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 425.835 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 468.235 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 510.235 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 552.635 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 594.635 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 637.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 679.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 721.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 763.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 805.835 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 847.835 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 890.235 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 932.235 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 974.635 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1016.635 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1059.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1101.035 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1143.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1185.435 -nets VSS  -layer B2 -width 0.650 -pitch_within_group 42.200 -start_low_ends coordinate  -start_low_ends_coordinate 174.210 -start_high_ends coordinate  -start_high_ends_coordinate 1226.800 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 217.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 259.485 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 301.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 343.485 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 385.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 427.485 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 469.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 510.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 553.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 594.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 637.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 678.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 721.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 762.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 805.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 846.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 889.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 930.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 973.085 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1014.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1056.285 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1098.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1140.285 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1182.685 -nets VDD  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 169.070 -start_high_ends coordinate  -start_high_ends_coordinate 1230.950 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 218.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 260.535 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 302.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 344.535 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 386.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 428.535 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 470.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 511.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 554.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 595.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 638.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 679.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 722.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 763.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 806.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 847.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 890.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 931.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 974.135 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1015.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1057.335 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1099.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1141.335 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1183.735 -nets VSS  -layer EA -width 0.650 -pitch_within_group 41.970 -start_low_ends coordinate  -start_low_ends_coordinate 170.740 -start_high_ends coordinate  -start_high_ends_coordinate 1229.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
