set_attribute -type boolean [get_pins pad56/PAD] is_pad true
set_attribute -type boolean [get_pins pad45/PAD] is_pad true
set_attribute -type boolean [get_pins pad43/PAD] is_pad true
set_attribute -type boolean [get_pins pad36/PAD] is_pad true
set_attribute -type boolean [get_pins pad34/PAD] is_pad true
set_attribute -type boolean [get_pins pad27/PAD] is_pad true
set_attribute -type boolean [get_pins pad25/PAD] is_pad true
set_attribute -type boolean [get_pins pad22/PAD] is_pad true
set_attribute -type boolean [get_pins pad17/PAD] is_pad true
set_attribute -type boolean [get_pins pad14/PAD] is_pad true
set_attribute -type boolean [get_pins pad11/PAD] is_pad true
set_attribute -type boolean [get_pins pad10/PAD] is_pad true
set_attribute -type boolean [get_pins pad3/PAD] is_pad true
